# ===================================================================
# SCRIPT 02: VISUALIZATION FOR FIGURE 1
# -------------------------------------------------------------------
# Description: This script generates the kernel density plot (Figure 1)
#              to visualize the distribution of 5C scores across the
#              identified latent profiles.
# Input:       "hesitancy_data_profiled.xlsx" (Generated by Script 01)
# Output:      "Figure1_Publication_Version.png" (The final plot)
# ===================================================================

# --- Step 0: Setup Environment ---
library(tidyverse)
library(readxl)
library(viridis)

# --- Step 1: Load Profiled Data ---
# This script reads the output file from the LPA analysis.
file_path <- "hesitancy_data_profiled.xlsx"
dat_final <- read_excel(file_path)

# --- Step 2: Data Preparation for Plotting ---
score_columns <- c("Calculation", "Collective", "Complacency", "Confidence", "Constraints")

dat_plot <- dat_final %>%
  mutate(
    profile = factor(profile,
                     levels = c(1, 2, 3, 4, 5), # Adjust levels if your profile numbers are different
                     labels = c("1. Willing but Obstructed", "2. Distrustful & Disengaged",
                                "3. Perceived Invulnerables", "4. Anxious Deliberators", "5. Passive Acceptors"))
  ) %>%
  pivot_longer(
    cols = all_of(score_columns),
    names_to = "Dimension",
    values_to = "Score"
  ) %>%
  mutate(
    Dimension = factor(Dimension, levels = score_columns)
  )

# --- Step 3: Generate the Plot ---
cat("Generating the final density plot...\n")

final_plot <- ggplot(dat_plot, aes(x = Score, colour = profile)) +
  geom_density(aes(fill = profile), linewidth = 0.9, alpha = 0.15, adjust = 2.0) +
  scale_color_viridis_d(option = "D") +
  scale_fill_viridis_d(option = "D") +
  facet_wrap(~ Dimension, ncol = 3, scales = "free_y") +
  labs(
    title = "Distribution of 5C Scale Scores Across Latent Profiles",
    x = "Scale Score (1-5)",
    y = "Density",
    colour = "Profile",
    fill = "Profile"
  ) +
  theme_bw(base_size = 14) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey92", color = "grey92"),
    strip.text = element_text(face = "bold")
  )

# --- Step 4: Save the Final Figure ---
output_figure_path <- "Figure1_Publication_Version.png"
ggsave(
  output_figure_path,
  plot = final_plot,
  width = 12,
  height = 8,
  dpi = 300
)
